### ISSUE TITLE
Merger is removing ring utilities 

### ISSUE THREAD

**Issue by greven** [zachdaniel/tails#11]
**Describe the bug**
Tails.classes/1 is removing ring-x utilities.

**To Reproduce**
Tails.classes("bg-gray-50 text-gray-600 ring-1 ring-inset ring-gray-500/10") 

**Expected behavior**
I expect in this case no classes to be removed as there isn't any conflicts to be merged, but the result of this is: "ring-inset bg-gray-50 text-gray-600 ring-gray-500/10" and it should have been "bg-gray-50 text-gray-600 ring-1 ring-inset ring-gray-500/10".
So **ring-1** is being removed!

**Runtime**
 - Elixir version: 1.14.4
 - Erlang version 25
 - OS MacOS ARM
 - Tails version {tails, "0.1.6"}

**Comment by zachdaniel** [comment]
Thanks for the report! It's the `/10` at the end of the color class :) Let me look at how we can work that into our current setup without significantly impacting compile times :)
