### ISSUE TITLE
Attributes with `-px` do not work

### ISSUE THREAD

**Issue by ravensiris** [zachdaniel/tails#19]
**Describe the bug**
Seems like merging attributes with `-px` does not work.

**To Reproduce**
```elixir
iex(2)> import Tails
Tails
iex(3)> classes(["p-px", "p-4"])
"p-4 p-px"
```

**Expected behavior**
It would replace a `p-px` class with `p-4`
```elixir
iex(2)> import Tails
Tails
iex(3)> classes(["p-px", "p-4"])
"p-4"
```

**Runtime**
 - Elixir version Elixir 1.16.0 (compiled with Erlang/OTP 26)
 - Erlang version Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:16:12] [ds:16:12:10] [async-threads:1] [jit:ns]
 - OS GNU/Linux
 - Tails version **main**(e623f70a103d124df78319adac695e5123d70ed2)

**Comment by zachdaniel** [comment]
Can you show me the tailwind docs on `p-px`? I can't find it.

**Comment by ravensiris** [comment]
Sure:
Here's the default spacing scale
https://tailwindcss.com/docs/customizing-spacing#default-spacing-scale

and here are the docs for padding:
https://tailwindcss.com/docs/padding
![image](https://github.com/zachdaniel/tails/assets/10886532/cc4e55ff-a1d3-413d-b6b6-b6e514e00b0b)

**Comment by zachdaniel** [comment]
I must be blind 😆 thanks. Looks like we'll need to special case `px`.
