### ISSUE TITLE
Bug: `align-text-` doesn't merge correctly

### ISSUE THREAD

**Issue by frankdugan3** [zachdaniel/tails#3]
**To Reproduce**
```elixir
iex(2)> Tails.classes(["align-text-bottom", "align-text-middle"])
"align-text-bottom align-text-middle"
```

**Expected behavior**
```elixir
Tails.classes(["align-text-bottom", "align-text-middle"])
"align-text-middle"
```

**Comment by zachdaniel** [comment]
<img width="817" alt="CleanShot 2023-02-13 at 23 39 59@2x" src="https://user-images.githubusercontent.com/5722339/218640943-dcfaf544-ed25-474f-a743-582963970d0b.png">
I don't see an `align-text-middle`...

**Comment by frankdugan3** [comment]
Ahh, sorry. That was a total PEBKAC... I meant to use `align-baseline`. :man_facepalming:
