### ISSUE TITLE
Support deeply-nested theme colors

### ISSUE THREAD

**Issue by rellen** [zachdaniel/tails#8]
Theme colors in tailwind can be deeply-nested, e.g. `"my_theme": {"neutral": {"gray": "#DDDDDD", ...}}`

These classes are not surfaced by Tails so it is not able to merge classes using them with other color-related classes.

I assume this is just a limitation in the implementation, not a conscious decision?  If so, here is a PR that improves the `Tails.Color.all_color_classes` function to support deeper-nested colors: https://github.com/zachdaniel/tails/pull/7

**Comment by zachdaniel** [comment]
Awesome report, and excellent fix!
